version: '3'
services:
  default-db:
    image: postgres:latest
    container_name: tt-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./data/init-scripts:/docker-entrypoint-initdb.d
  message-broker:
    image: rabbitmq:3-management
    container_name: tt-rabbitmq-container
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  memory-db:
    image: redis:latest
    container_name: tt-redis-container
    ports:
      - "6379:6379"
  api:
    image: farneser/task-tracker-api:latest
    container_name: tt-api-container
    ports:
      - "8080:8080"
    depends_on:
      - default-db
      - message-broker
    env_file:
      - .env
  scheduler:
    image: farneser/task-tracker-scheduler:latest
    container_name: tt-scheduler-container
    depends_on:
      - default-db
      - message-broker
    env_file:
      - .env
  email-sender:
    image: farneser/task-tracker-email-sender:latest
    container_name: tt-email-sender-container
    depends_on:
      - message-broker
    env_file:
      - .env
